steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['test', 'allure:report']
artifacts:
  objects:
    location: 'gs://iz-allure-reports/automated'
    paths: ['/workspace/target/site/allure-maven-plugin']